// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlS-IJDAM_rqGrAWs96ooQy_fYKWMQkmQ',
    appId: '1:824748580572:web:f27f7e6257c29c3bad9e19',
    messagingSenderId: '824748580572',
    projectId: 'puvogcoin',
    authDomain: 'puvogcoin.firebaseapp.com',
    storageBucket: 'puvogcoin.appspot.com',
    measurementId: 'G-8X7D7VEQQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy7BNFnJn4pLWcogMGQa1wp9aViRsZeNk',
    appId: '1:824748580572:android:b84438362fc19633ad9e19',
    messagingSenderId: '824748580572',
    projectId: 'puvogcoin',
    storageBucket: 'puvogcoin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAMO0rz1doexv-8e2HRiFysioy06RE0oI',
    appId: '1:824748580572:ios:08aa8de3029ced80ad9e19',
    messagingSenderId: '824748580572',
    projectId: 'puvogcoin',
    storageBucket: 'puvogcoin.appspot.com',
    iosClientId:
        '824748580572-uklb6jf6e322j4ir53hng29mppenep7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitcoinApp',
  );
}
